import { Outfit } from "next/font/google";
import "./globals.css";
import Layout from "./Components/Layout";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
